SELECT tblOrgs.Org, sqryBOM.ASSY, sqryBOM.COMPT, sqryBOM.IMPLEMENTATION_DATE, sqryBOM.ORGANIZATION_ID, sqryBOM.DISABLE_DATE, sqryBOM.QTY, sqryBOM.INVERSE_QTY, sqryBOM.ASSYDESCRIPTION, sqryBOM.ASSYSTATUS, sqryBOM.COMPDESCRIPTION, sqryBOM.COMPSTATUS, sqryBOM.COMPONENT_ITEM_ID, sqryBOM.ASSEMBLY_ITEM_ID
FROM tblOrgs RIGHT JOIN sqryBOM ON tblOrgs.ID = sqryBOM.ORGANIZATION_ID
GROUP BY tblOrgs.Org, sqryBOM.ASSY, sqryBOM.COMPT, sqryBOM.IMPLEMENTATION_DATE, sqryBOM.ORGANIZATION_ID, sqryBOM.DISABLE_DATE, sqryBOM.QTY, sqryBOM.INVERSE_QTY, sqryBOM.ASSYDESCRIPTION, sqryBOM.ASSYSTATUS, sqryBOM.COMPDESCRIPTION, sqryBOM.COMPSTATUS, sqryBOM.COMPONENT_ITEM_ID, sqryBOM.ASSEMBLY_ITEM_ID
HAVING (((tblOrgs.Org) Is Not Null));

