SELECT
    si.SEGMENT1 as NAM,
    si.DESCRIPTION,
    ci.CUSTOMER_ITEM_NUMBER,
    c.CUSTOMER_NAME,
    ic.INACTIVE_FLAG,
    ci.INACTIVE_FLAG,
    ci.CUSTOMER_ITEM_DESC
FROM
    APPS.XXCUS_CUSTOMERS C
    INNER JOIN INV.MTL_CUSTOMER_ITEMS ci ON c.CUSTOMER_ID = ci.CUSTOMER_ID
    INNER JOIN INV.MTL_CUSTOMER_ITEM_XREFS ic ON ic.CUSTOMER_ITEM_ID = ci.CUSTOMER_ITEM_ID
    INNER JOIN INV.MTL_SYSTEM_ITEMS_B si ON si.INVENTORY_ITEM_ID = ic.INVENTORY_ITEM_ID
GROUP BY
    si.SEGMENT1,
    si.DESCRIPTION,
    ci.CUSTOMER_ITEM_NUMBER,
    c.CUSTOMER_NAME,
    ic.INACTIVE_FLAG,
    ci.INACTIVE_FLAG,
    ci.CUSTOMER_ITEM_DESC
   HAVING (CUSTOMER_ITEM_NUMBER LIKE '%86466%');
