SELECT
    Max(NEW_ITEM_REVISION) AS REV
FROM
    ENG.ENG_REVISED_ITEMS RI
    INNER JOIN INV.MTL_SYSTEM_ITEMS_B SI ON RI.REVISED_ITEM_ID = SI.INVENTORY_ITEM_ID
WHERE
    (
        (RI.IMPLEMENTATION_DATE Is Not Null)
        AND (SI.SEGMENT1='29100'));
