SELECT APPS_MTL_SYSTEM_ITEMS.SEGMENT1 AS NAM, tblOrgs.Org, splitString([DESCRIPTION],".",0) AS [Indicator], splitString([DESCRIPTION],".",1) AS Type, splitString([DESCRIPTION],".",2) AS Material, splitString([DESCRIPTION],".",3) AS Grade, splitString([DESCRIPTION],".",4) AS Segment5, splitString([DESCRIPTION],".",5) AS Color, APPS_MTL_SYSTEM_ITEMS.ITEM_TYPE, APPS_MTL_SYSTEM_ITEMS.INVENTORY_ITEM_STATUS_CODE
FROM APPS_MTL_SYSTEM_ITEMS LEFT JOIN tblOrgs ON APPS_MTL_SYSTEM_ITEMS.ORGANIZATION_ID = tblOrgs.ID
WHERE (((tblOrgs.Org) Is Not Null) AND ((splitString([DESCRIPTION],".",0))="MATERIAL") AND ((APPS_MTL_SYSTEM_ITEMS.ITEM_TYPE)="RM" Or (APPS_MTL_SYSTEM_ITEMS.ITEM_TYPE)="PH") AND ((APPS_MTL_SYSTEM_ITEMS.INVENTORY_ITEM_STATUS_CODE)<>"Inactive"));

