SELECT
    INVENTORY_ITEM_ID,
    SEGMENT1,
    INVENTORY_ITEM_STATUS_CODE,
    ITEM_TYPE,
    DESCRIPTION
FROM
    INV.MTL_SYSTEM_ITEMS_B
WHERE
    SEGMENT1 = '26589'
GROUP BY
    SEGMENT1,
    INVENTORY_ITEM_ID,
    INVENTORY_ITEM_STATUS_CODE,
    ITEM_TYPE,
    DESCRIPTION
