SELECT
    msi.SEGMENT1 AS PN,
    mcv.SEGMENT3 AS Standard_Cost_Owner
FROM
    INV.MTL_ITEM_CATEGORIES mic
    JOIN INV.MTL_SYSTEM_ITEMS_B msi ON mic.INVENTORY_ITEM_ID = msi.INVENTORY_ITEM_ID
    LEFT JOIN APPS.MTL_CATEGORIES_VL mcv ON mic.CATEGORY_ID = mcv.CATEGORY_ID
where
    STRUCTURE_ID = 50349
    AND msi.SEGMENT1 = '{PART_NUMBER}'
GROUP BY
    msi.SEGMENT1,
    mcv.SEGMENT3;
