SELECT
    SIFTBL.NIFCO_PART_NUMBER,
    SIFTBL.PART_DESCRIPTION,
    SIFTBL.SIFNUM,
    'SIF Assy' as SIF_TYPE
FROM
    APPS.Q_SIF_NEW_ASSEMBLED_PART_V SIFTBL
UNION
SELECT
    SIFTBL.NIFCO_PART_NUMBER,
    SIFTBL.PART_DESCRIPTION,
    SIFTBL.SIFNUM,
    'SIF Mold' as SIF_TYPE
FROM
    APPS.Q_SIF_NEW_MOLDED_PART_V SIFTBL
UNION
SELECT
    SIFTBL.NIFCO_PART_NUMBER,
    SIFTBL.PART_DESCRIPTION,
    SIFTBL.SIFNUM,
    'SIF Purch' as SIF_TYPE
FROM
    APPS.Q_SIF_NEW_PURCHASING_PART_V SIFTBL
